---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/local.yml
    - env_vars/postgresql.yml

  roles:
    - base
    - joshualund.golang
    - htop
    # - ANXS.postgresql
    # - db
    - goapp
    - supervisor